name: deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: notice-seat-availability
          runtime: python39
          credentials: ${{ secrets.gcp_credentials }}
          entry_point: run
          region: asia-northeast1
          source_dir: .
          env_vars: LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
